version: '3.9'

services:
  tarotai:
    build: .
    ports:
      - "8000:8000"  # змінити під порт, який використовує app.py
    volumes:
      - .:/app
    env_file:
      - config/.env
    restart: always
